#端口
server:
  port: 8081
spring:
  datasource:
    username: choice
    password: choice123
    url: jdbc:mysql://rm-bp12ec7ixn03ie08yto.mysql.rds.aliyuncs.com:3306/choice
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/登录注册页面/
      suffix: .jsp
    static-path-pattern: /**
logging:
  file:
    name: /spring/log
